# Generated by Django 6.0.6 on 2026-06-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelmodel',
            old_name='summary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='novelmodel',
            name='is_fanfic',
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='novel_type',
            field=models.CharField(blank=True, choices=[('fanfic', 'Fanfic'), ('translate', 'Translate'), ('own_creation', 'Own Creation')], default='own_creation', max_length=20, null=True),
        ),
    ]
