# Generated by Django 5.2.11 on 2026-05-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slidermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelmodel',
            options={'verbose_name': 'Novel', 'verbose_name_plural': 'Novels'},
        ),
        migrations.AlterModelTable(
            name='novelmodel',
            table='novels',
        ),
    ]
