# Generated by Django 6.0.6 on 2026-06-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_novelpushsubscriptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardmodel',
            name='reward_type',
            field=models.CharField(choices=[('gem_gift', 'Gem Gift (Login Reward)'), ('free_read', 'Free Read (All Chapters Free)'), ('discount_read', 'Discount Read (All Chapters 1 Gem)')], default='gem_gift', max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardmodel',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='gem_gift အတွက်သာ သုံး၊ free_read/discount_read မှာ 0 ထားပါ'),
        ),
        migrations.AlterField(
            model_name='rewardmodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='None ဆိုရင် user အားလုံးအတွက်', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
