# Generated by Django 5.2.11 on 2026-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
