# Generated by Django 6.0.6 on 2026-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rewardmodel_reward_type_alter_rewardmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='free_gem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
