# Generated by Django 5.2.11 on 2026-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_novelmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
