# Generated by Django 6.0.6 on 2026-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usermodel_free_gem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpurchasemodel',
            name='free_gems_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterpurchasemodel',
            name='paid_gems_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
