# Generated by Django 5.2.11 on 2026-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_novelmodel_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='is_fanfic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
