# Generated by Django 6.0.6 on 2026-06-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chapterpurchasemodel_free_gems_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmodel',
            name='is_popular',
        ),
    ]
