# Generated by Django 6.0.6 on 2026-07-18 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_novelmodel_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='delete_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='delete_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chapter_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='delete_pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_chapter_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='delete_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='delete_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_novel_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='delete_pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_novel_deletions', to=settings.AUTH_USER_MODEL),
        ),
    ]
