# Generated by Django 5.2.12 on 2026-10-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_campaign_multi_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
