# Generated by Django 5.2.11 on 2026-05-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chapterpurchasemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelchaptermodel',
            name='is_free',
        ),
    ]
