# Generated by Django 5.2.11 on 2026-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_novelchaptermodel_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmodel',
            name='is_free',
        ),
        migrations.AddField(
            model_name='novelchaptermodel',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
