# Generated by Django 5.2.12 on 2026-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chaptermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
