# Generated by Django 5.2.11 on 2026-06-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_novelmodel_is_free_novelchaptermodel_is_free'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovelChapterModel',
            new_name='ChapterModel',
        ),
    ]
